"""Pydantic request and response schemas."""

from app.schemas.requests import (
    ActionRequest,
    AbandonedCartRequest,
    AutomationEventRequest,
    AutomationRuleRequest,
    AutomationRuleUpdateRequest,
    DeliveredFollowupRequest,
    DocumentRequest,
    EcommerceConnectionRequest,
    EcommerceConnectionUpdateRequest,
    EcommerceProductSyncRequest,
    EcommerceSyncRequest,
    OrderRequest,
    RetryWebhookEventsRequest,
    ScrapeRequest,
    SendTemplateRequest,
    SendMessageRequest,
    MessageTemplateRequest,
)

__all__ = [
    "ActionRequest",
    "AbandonedCartRequest",
    "AutomationEventRequest",
    "AutomationRuleRequest",
    "AutomationRuleUpdateRequest",
    "DeliveredFollowupRequest",
    "DocumentRequest",
    "EcommerceConnectionRequest",
    "EcommerceConnectionUpdateRequest",
    "EcommerceProductSyncRequest",
    "EcommerceSyncRequest",
    "OrderRequest",
    "RetryWebhookEventsRequest",
    "ScrapeRequest",
    "SendTemplateRequest",
    "SendMessageRequest",
    "MessageTemplateRequest",
]
