class IntegrationProvider:
    WHATSAPP_BUSINESS = "WHATSAPP_BUSINESS"
    SHOPIFY = "SHOPIFY"
    WOOCOMMERCE = "WOOCOMMERCE"
    GOOGLE_ADS = "GOOGLE_ADS"
    META_ADS = "META_ADS"


class IntegrationStatus:
    CONNECTED = "CONNECTED"
    NEEDS_REAUTH = "NEEDS_REAUTH"
    ERROR = "ERROR"
    DISCONNECTED = "DISCONNECTED"
